---
- hosts: all
  become: true 
  tasks:

  - name: Update packages
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: add php support for appache
    apt:
      name: libapache2-mod-php
      state: latest 
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
