---
- hosts: all 
  become: true 
  tasks:

  - name: install updates
    tags : always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true 
  tasks:

  - name: install apache2 package and add php support for appache
    tags: apache 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest 

- hosts: db_server
  become: true 
  tasks:


  - name: install mariadb package
    tags: database 
    apt: 
      name: 
        - mariadb-server
      state: latest 
    
- hosts: file_server    
  become: true
  tasks: 

  - name : intall samba package
    package: 
         name : samba
         state: latest 
